on:
  workflow_call:
    inputs:
      args:
        type: string
        default: 'check --output-format github'
        description: 'Arguments passed to jarl'

name: Lint R Code

jobs:
  r-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: etiennebacher/setup-jarl@v0.1.1
        with:
          args: ${{ inputs.args }}
